import Head from 'next/head';
import styles from '../../styles/download.module.css';

const Download = () => {
  return (
    <>
      <Head>
        <title>Download</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div className={styles.container}>
        <button className={styles.download_button}>Скачать игру</button>
      </div>
    </>
  );
};

export default Download;
