import Head from 'next/head';

const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <h2>About</h2>
        <p>
          Perfect World — это популярнейшая MMORPG, в которой вас ждет множество захватывающих приключений. Выберите
          один из 15 классов и отправляйтесь исследовать огромный фэнтезийный мир. Здесь найдется занятие для каждого —
          ведь игра сочетает в себя хардкорное PvP, увлекательное PvE и мощную социальную систему. В Perfect World можно
          не только путешествовать на быстрых ездовых питомцах и плавать в многочисленных водоемах. У каждого героя
          Идеального Мира есть возможность летать и сражаться на собственных крыльях!
        </p>
      </div>
    </>
  );
};

export default About;
