import Head from 'next/head';

const Community = () => {
  return (
    <>
      <Head>
        <title>Community</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <h2>Community</h2>
      </div>
    </>
  );
};

export default Community;
