import Head from 'next/head';

const Download = () => {
  return (
    <>
      <Head>
        <title>Download</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <h2>Download</h2>
      </div>
    </>
  );
};

export default Download;
