import Head from 'next/head';

const Media = () => {
  return (
    <>
      <Head>
        <title>Media</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <h2>Media</h2>
      </div>
    </>
  );
};

export default Media;
