import Head from 'next/head';

const Support = () => {
  return (
    <>
      <Head>
        <title>Support</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <div>
        <h2>Support</h2>
      </div>
    </>
  );
};

export default Support;
